import type { Metadata } from "next"
import "../styles/globals.css"
import "../styles/reset.css"
import MobileViewLayout from "@/components/layout/MobileViewLayout"
import { Pixel, Pretendard } from "@/fonts"
import { authOptions } from "./api/auth/[...nextauth]/auth"
import { getServerSession } from "next-auth"
import { AuthProvider } from "@/providers/AuthProvider"
import ReactQueryProvider from "@/providers/ReactQueryProvider"
import { cn } from "@/utils/cn"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <body className={cn(Pretendard.variable, Pixel.variable)}>
        <ReactQueryProvider>
          <AuthProvider session={session}>
            <div id="modal" />
            <MobileViewLayout>{children}</MobileViewLayout>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
