import type { Metadata } from "next"
import "../styles/globals.css"
import "../styles/reset.css"
import MobileViewLayout from "../components/layout/MobileViewLayout"
import { Pretendard } from "@/fonts"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={Pretendard.variable}>
        <MobileViewLayout>{children}</MobileViewLayout>
      </body>
    </html>
  )
}
