import { Pretendard } from "@/fonts"
import { ColorKeyType, generateColorPalette, generateCSSVariables } from "@/utils/setDocumentColor"
import type { Metadata } from "next"
import { cookies } from "next/headers"
import MobileViewLayout from "../components/layout/MobileViewLayout"
import "../styles/globals.css"
import "../styles/reset.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  //#region palette setting
  const cookieStore = await cookies()
  let cssVariables = ""
  const colorKeys: ColorKeyType[] = ["primary", "secondary"]
  colorKeys.forEach((key) => {
    const color = cookieStore.get(key)?.value
    if (color) {
      const palette = generateColorPalette(color)
      cssVariables += generateCSSVariables(palette, key, color) + "\n"
    }
  })
  //endregion palette setting

  return (
    <html lang="en">
      <head>
        <style>{`
          :root {
            ${cssVariables}
          }
        `}</style>
      </head>
      <body className={Pretendard.variable}>
        <MobileViewLayout>{children}</MobileViewLayout>
      </body>
    </html>
  )
}
