/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query"
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from "@tanstack/react-query"
import type { QuestionCreateRequest, QuestionCreateResponse, QuestionResponse, TodayQuestionResponse } from ".././model"
import { customInstance } from ".././clientInstance"
import type { ErrorType, BodyType } from ".././clientInstance"

export const createQuestion = (
  channelId: string,
  questionCreateRequest: BodyType<QuestionCreateRequest>,
  signal?: AbortSignal
) => {
  return customInstance<QuestionCreateResponse>({
    url: `/api/channels/${channelId}/questions`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: questionCreateRequest,
    signal
  })
}

export const getCreateQuestionMutationOptions = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestion>>,
    TError,
    { channelId: string; data: BodyType<QuestionCreateRequest> },
    TContext
  >
}): UseMutationOptions<
  Awaited<ReturnType<typeof createQuestion>>,
  TError,
  { channelId: string; data: BodyType<QuestionCreateRequest> },
  TContext
> => {
  const mutationKey = ["createQuestion"]
  const { mutation: mutationOptions } = options
    ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createQuestion>>,
    { channelId: string; data: BodyType<QuestionCreateRequest> }
  > = (props) => {
    const { channelId, data } = props ?? {}

    return createQuestion(channelId, data)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateQuestionMutationResult = NonNullable<Awaited<ReturnType<typeof createQuestion>>>
export type CreateQuestionMutationBody = BodyType<QuestionCreateRequest>
export type CreateQuestionMutationError = ErrorType<unknown>

export const useCreateQuestion = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createQuestion>>,
    TError,
    { channelId: string; data: BodyType<QuestionCreateRequest> },
    TContext
  >
}): UseMutationResult<
  Awaited<ReturnType<typeof createQuestion>>,
  TError,
  { channelId: string; data: BodyType<QuestionCreateRequest> },
  TContext
> => {
  const mutationOptions = getCreateQuestionMutationOptions(options)

  return useMutation(mutationOptions)
}
export const findTodayQuestionByChannel = (channelId: string, signal?: AbortSignal) => {
  return customInstance<TodayQuestionResponse>({
    url: `/api/channels/${channelId}/questions/today`,
    method: "GET",
    signal
  })
}

export const getFindTodayQuestionByChannelQueryKey = (channelId: string) => {
  return [`/api/channels/${channelId}/questions/today`] as const
}

export const getFindTodayQuestionByChannelQueryOptions = <
  TData = Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findTodayQuestionByChannel>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getFindTodayQuestionByChannelQueryKey(channelId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findTodayQuestionByChannel>>> = ({ signal }) =>
    findTodayQuestionByChannel(channelId, signal)

  return { queryKey, queryFn, enabled: !!channelId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindTodayQuestionByChannelQueryResult = NonNullable<Awaited<ReturnType<typeof findTodayQuestionByChannel>>>
export type FindTodayQuestionByChannelQueryError = ErrorType<unknown>

export function useFindTodayQuestionByChannel<
  TData = Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findTodayQuestionByChannel>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
          TError,
          Awaited<ReturnType<typeof findTodayQuestionByChannel>>
        >,
        "initialData"
      >
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindTodayQuestionByChannel<
  TData = Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findTodayQuestionByChannel>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
          TError,
          Awaited<ReturnType<typeof findTodayQuestionByChannel>>
        >,
        "initialData"
      >
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindTodayQuestionByChannel<
  TData = Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findTodayQuestionByChannel>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindTodayQuestionByChannel<
  TData = Awaited<ReturnType<typeof findTodayQuestionByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findTodayQuestionByChannel>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindTodayQuestionByChannelQueryOptions(channelId, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}

export const findQuestionsByChannel = (channelId: string, signal?: AbortSignal) => {
  return customInstance<QuestionResponse[]>({ url: `/api/channels/${channelId}/questions/all`, method: "GET", signal })
}

export const getFindQuestionsByChannelQueryKey = (channelId: string) => {
  return [`/api/channels/${channelId}/questions/all`] as const
}

export const getFindQuestionsByChannelQueryOptions = <
  TData = Awaited<ReturnType<typeof findQuestionsByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findQuestionsByChannel>>, TError, TData>> }
) => {
  const { query: queryOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getFindQuestionsByChannelQueryKey(channelId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof findQuestionsByChannel>>> = ({ signal }) =>
    findQuestionsByChannel(channelId, signal)

  return { queryKey, queryFn, enabled: !!channelId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof findQuestionsByChannel>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindQuestionsByChannelQueryResult = NonNullable<Awaited<ReturnType<typeof findQuestionsByChannel>>>
export type FindQuestionsByChannelQueryError = ErrorType<unknown>

export function useFindQuestionsByChannel<
  TData = Awaited<ReturnType<typeof findQuestionsByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof findQuestionsByChannel>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findQuestionsByChannel>>,
          TError,
          Awaited<ReturnType<typeof findQuestionsByChannel>>
        >,
        "initialData"
      >
  }
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindQuestionsByChannel<
  TData = Awaited<ReturnType<typeof findQuestionsByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findQuestionsByChannel>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findQuestionsByChannel>>,
          TError,
          Awaited<ReturnType<typeof findQuestionsByChannel>>
        >,
        "initialData"
      >
  }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindQuestionsByChannel<
  TData = Awaited<ReturnType<typeof findQuestionsByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findQuestionsByChannel>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindQuestionsByChannel<
  TData = Awaited<ReturnType<typeof findQuestionsByChannel>>,
  TError = ErrorType<unknown>
>(
  channelId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof findQuestionsByChannel>>, TError, TData>> }
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFindQuestionsByChannelQueryOptions(channelId, options)

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  query.queryKey = queryOptions.queryKey

  return query
}
