/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { AnswerQuestionDTO } from "./answerQuestionDTO"
import type { AnswerResponse } from "./answerResponse"
import type { PageParamResponse } from "./pageParamResponse"

export interface AnswerShowAllResponse {
  signalCount?: number
  questionDTO?: AnswerQuestionDTO
  answerList?: AnswerResponse[]
  pageParamResponse?: PageParamResponse
}
