/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { AnswerWriteResponse } from "./answerWriteResponse"

export interface ApiAnswerWriteResponse {
  result?: Result
  body?: AnswerWriteResponse
}
