/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { ChannelJoinResponse } from "./channelJoinResponse"

export interface ApiChannelJoinResponse {
  result?: Result
  body?: ChannelJoinResponse
}
