/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { ChannelShowAllResponse } from "./channelShowAllResponse"

export interface ApiListChannelShowAllResponse {
  result?: Result
  body?: ChannelShowAllResponse[]
}
