/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { ChannelFriendResponse } from "./channelFriendResponse"

export interface ApiListChannelFriendResponse {
  result?: Result
  body?: ChannelFriendResponse[]
}
