/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { MemberCodeNameResponse } from "./memberCodeNameResponse"

export interface ApiMemberCodeNameResponse {
  result?: Result
  body?: MemberCodeNameResponse
}
