/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { MemberResponse } from "./memberResponse"

export interface ApiMemberResponse {
  result?: Result
  body?: MemberResponse
}
