/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { Result } from "./result"
import type { RefreshTokenResponse } from "./refreshTokenResponse"

export interface ApiRefreshTokenResponse {
  result?: Result
  body?: RefreshTokenResponse
}
