/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export interface ChannelMemberDto {
  channelMemberId?: number
  codeName?: string
  profileImageUrl?: string
}
