/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { ChannelFriendResponse } from "./channelFriendResponse"
import type { PageParamResponse } from "./pageParamResponse"

export interface ChannelFriendShowAllResponse {
  channelFriendResponseList?: ChannelFriendResponse[]
  pageParamResponse?: PageParamResponse
}
