/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export interface ChannelMemberProfileResponse {
  channelMemberId?: number
  codeName?: string
  profileImageUrl?: string
  isTodayQuestioner?: boolean
}
