/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { ChannelShowResponse } from "./channelShowResponse"
import type { PageParamResponse } from "./pageParamResponse"

export interface ChannelShowAllResponse {
  channelShowResponse?: ChannelShowResponse[]
  pageParamResponse?: PageParamResponse
}
