/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { PageParamRequest } from "./pageParamRequest"

export type FindQuestionsByMemberParams = {
  pageParamRequest: PageParamRequest
  sort?: string
}
