/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { MyChannelMemberResponse } from "./myChannelMemberResponse"
import type { PageParamResponse } from "./pageParamResponse"

export interface MyChannelMemberShowAllResponse {
  myChannelMemberResponse?: MyChannelMemberResponse[]
  pageParamResponse?: PageParamResponse
}
