/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export interface PageParamResponse {
  currentPage?: number
  size?: number
  totalElements?: number
  totalPages?: number
  hasNext?: boolean
}
