/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */
import type { QuestionResponse } from "./questionResponse"
import type { PageParamResponse } from "./pageParamResponse"

export interface QuestionShowAllResponse {
  questionResponse?: QuestionResponse[]
  pageParamResponse?: PageParamResponse
}
