/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export interface TodayQuestionResponse {
  signalCount?: number
  isExist?: boolean
  content?: string
  writer?: string
  time?: string
}
