/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export type TutorialResponseTutorialStatus =
  (typeof TutorialResponseTutorialStatus)[keyof typeof TutorialResponseTutorialStatus]

export const TutorialResponseTutorialStatus = {
  PASS: "PASS",
  NON_PASS: "NON_PASS"
} as const
