/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PickiTalki API
 * OpenAPI spec version: 1.0
 */

export interface UserResponse {
  accessToken?: string
  refreshToken?: string
  expiredAccessToken?: number
  userName?: string
  channelCount?: number
  channelId?: string
}
